### ISSUE TITLE
Create a Q/A for the demo:  Structure People Dimension in Portfolio Management

### ISSUE THREAD

**Issue by RehabAbotalep** [MohamedRadwan-DevOps/devops-step-by-step#143]
Create a Q/A for the demo on how to create a new project in an Azure DevOps organization, create multiple teams in the created project, and how structure people dimension in the created teams.

**Comment by RehabAbotalep** [comment]
@fadysaad66 Please confirm that you will work on that item.

**Comment by RehabAbotalep** [comment]
@fadysaad66 When start working on it, kindly mention me here to move it to in-progress.

**Comment by RehabAbotalep** [comment]
@fadysaad66 OK, when you finish the assigned in-progress one, I will move this to in-progress.
Please note that don't work at two PIBs at the same time.
Check the [Contribution Culture](https://github.com/MohamedRadwan-DevOps/devops-step-by-step/blob/main/source/contribution/contribution-culture.md), plz.

**Comment by RehabAbotalep** [comment]
@MohamedRadwan-DevOps and I agreed that we want to complete this issue as soon as possible, so I will reassign it.
Thanks so much for your previous contribution, appreciated.
@fadysaad66

**Comment by AhalimZaki** [comment]
@RehabAbotalep 
http://devopsvisionsqa.mohamedradwan.com/?qa=543/how-to-structure-people-dimension-in-portfolio-management
