### ISSUE TITLE
Create a Q/A for the demo: Use git as a remote repo from the local one (clone, pull, push, etc) Azure Repo

### ISSUE THREAD

**Issue by RehabAbotalep** [MohamedRadwan-DevOps/devops-step-by-step#152]
Create a Q/A on how to use Git as a remote repo from the local one on Azure Repo, and how to understand and use the different Git commands like clone, pull, push and so on.

**Comment by RehabAbotalep** [comment]
@muhammedeid Please confirm working on this item.

**Comment by muhammedeid** [comment]
@RehabAbotalep yes Confirmed

**Comment by muhammedeid** [comment]
@RehabAbotalep  I can start now and you also can move stages for this issues to in In progress.

**Comment by muhammedeid** [comment]
@AhalimZaki you can review now.

**Comment by AhalimZaki** [comment]
In the 2nd answer, you were amazing following the numeration i hope you will follow that in future posts.

However, in the first answer, i edited the following bullet points with a number instead.
in the following steps, i made small changes.
8.1 to git log and added gitlog quote for the command.
9.1, 10.1.2, 11.1, 14.1.2, 16.1,2,3,4,5,6.

Please consider doing the same stander in the future.

Also, i have updated the guidelines with a new section containing in-depth numeration and a tool that can help you with 
grammar and Coordination of your demo.

**Comment by RehabAbotalep** [comment]
@AhalimZaki @muhammedeid I have made some edits, kindly check.
@MohamedRadwan-DevOps Your final review, please.
http://devopsvisionsqa.mohamedradwan.com/?qa=526/what-steps-remote-repo-from-local-clone-pull-push-azure-repo&show=532#a532
