### ISSUE TITLE
Fix all images path issue in the Q/As that added by Kareem

### ISSUE THREAD

**Issue by RehabAbotalep** [MohamedRadwan-DevOps/devops-step-by-step#159]
Fix images path in the added Q/As to be uploaded to the Q/A platform not copied and pasted from Stackoverflow.

**Comment by RehabAbotalep** [comment]
@Kareem4006 Please confirm.

**Comment by Kareem4006** [comment]
@RehabAbotalep Confirmed, I fixed them all.

**Comment by RehabAbotalep** [comment]
@MohamedRadwan-DevOps I have reviewed them all, fixed.
