### ISSUE TITLE
Review and Improve Module 2 Demos

### ISSUE THREAD

**Issue by AhalimZaki** [MohamedRadwan-DevOps/devops-step-by-step#221]

**Comment by AhalimZaki** [comment]
Demo 1: Create and examine Win 11 VM from the gallery. 
[ Re-structured the whole question] need to go over it later for quality.
https://devopsvisionsqa.mohamedradwan.com/?qa=290/what-are-the-steps-to-create-and-examine-win-from-the-gallery


Demo 2:Create and examine Ubuntu 20.04 VM from the gallery.   
is ok 
https://devopsvisionsqa.mohamedradwan.com/?qa=506/what-are-the-steps-create-examine-ubuntu-created-from-gallery

Demo  3: Create and examine Ubuntu 18.04 VM from the gallery.
Guidelines-Quality-Control.
https://devopsvisionsqa.mohamedradwan.com/?qa=296/what-are-the-steps-create-and-examine-ubuntu-from-the-gallery


Demo  4 : Create and examine Windows 10 from ISO.
Guidelines-Quality-Control.
https://devopsvisionsqa.mohamedradwan.com/?qa=364/what-are-the-steps-to-create-and-examine-windows-10-from-iso

Demo  5 : Creating a Console App with business logic inside.
Guidelines-Quality-Control.
https://devopsvisionsqa.mohamedradwan.com/?qa=310/what-are-steps-creating-console-with-business-logic-inside

Demo 6: Creating a Desktop App with business logic inside.
Guidelines-Quality-Control, a bit of re-structure for steps later.
https://devopsvisionsqa.mohamedradwan.com/?qa=309/what-steps-create-desktop-application-business-logic-inside

Demo 7: Creating an API App with business logic inside.
Guidelines-Quality-Control.
https://devopsvisionsqa.mohamedradwan.com/?qa=243/what-are-the-steps-create-the-api-with-business-logic-inside

Demo 8: Creating a Class library and moving the business logic inside it.
Guidelines-Quality-Control, better pics quality.
https://devopsvisionsqa.mohamedradwan.com/?qa=306/what-steps-create-class-library-move-business-logic-inside

Demo 9: Amend the Console App to use the class library.
Guidelines-Quality-Control. better pics quality.
https://devopsvisionsqa.mohamedradwan.com/?qa=287/what-are-the-steps-amend-the-console-app-use-the-class-library&show=288#a288

Demo 10:Amend the API App to use the class library.
re-structure the images are not constant.
https://devopsvisionsqa.mohamedradwan.com/?qa=298/what-are-the-steps-to-amend-api-app-to-use-the-class-library


Demo 11: Amend the Console App to use the API.
Images re-structure & Quality.
https://devopsvisionsqa.mohamedradwan.com/?qa=303/what-are-the-steps-to-amend-the-console-app-to-use-the-api

Demo 12: Amend the Desktop App to use the API.
Guidelines-Quality-Control.
https://devopsvisionsqa.mohamedradwan.com/?qa=462/what-are-the-steps-to-amend-the-desktop-app-to-use-the-api&show=468#a468

Demo 13: Create another API that consumes the 1st API.
Need fully re-work. DarkMode doesn't show anything. (done).
https://devopsvisionsqa.mohamedradwan.com/?qa=481/what-are-the-steps-create-another-api-that-consumes-the-1st-api

Demo 15: Package API and Deploy it to local IIS and expose to public.
Is ok.
https://devopsvisionsqa.mohamedradwan.com/?qa=520/what-are-the-steps-package-and-deploy-the-api-app-expose-public

Demo 16: Intro to NuGet package management.
Guidelines-Quality-Control.
https://devopsvisionsqa.mohamedradwan.com/?qa=363/what-are-the-steps-to-get-intro-nuget-package-management

Demo 17: Package the class library and publish it to nuget package.
Done the missing step of the publish lib, Still need Guidelines-Quality-Control.
https://devopsvisionsqa.mohamedradwan.com/?qa=369/what-are-steps-package-class-library-publish-nuget-package


Demo 18: Replace the class library in the API with the nuget package library.
https://devopsvisionsqa.mohamedradwan.com/?qa=522/what-steps-replace-class-library-with-nuget-package-library
is ok.

Demo 19: Create Unit test for the class library.
https://devopsvisionsqa.mohamedradwan.com/?qa=302/what-are-the-steps-to-create-a-unit-test-for-the-class-library
Guidelines-Quality-Control.

Demo 20: Explain and examine code coverage, code metrics.
more description needed (Done). 
Guidelines-Quality-Control, needs better pic quality.
https://devopsvisionsqa.mohamedradwan.com/?qa=316/what-are-the-steps-to-examine-code-coverage-code-metrics


Demo 21: Configure unit test run-settings to generate test results and code coverage.
couldn't find it.

Demo 22: Examine a UI test and run it.
Guidelines-Quality-Control.
https://devopsvisionsqa.mohamedradwan.com/?qa=368/what-are-the-steps-to-perform-ui-test

**Comment by RehabAbotalep** [comment]
@AhalimZaki Reviewed, thanks so much for your effort.
