### ISSUE TITLE
More about Docker and how to use Docker compose

### ISSUE THREAD

**Issue by AhalimZaki** [MohamedRadwan-DevOps/devops-step-by-step#270]
Create a Q/A for the demo: More about Docker and how to use Docker compose.

**Comment by AhalimZaki** [comment]
[Demo Link](http://devopsvisionsqa.mohamedradwan.com/?qa=603/what-are-the-steps-more-about-docker-and-how-use-docker-compose&show=604#a604)

**Comment by RehabAbotalep** [comment]
> [Demo Link](http://devopsvisionsqa.mohamedradwan.com/?qa=603/what-are-the-steps-more-about-docker-and-how-use-docker-compose&show=604#a604)

I have reviewed it, please your final review. @MohamedRadwan-DevOps
