### ISSUE TITLE
Create a Q/A for the demo: Managing git conflicts

### ISSUE THREAD

**Issue by RehabAbotalep** [MohamedRadwan-DevOps/devops-step-by-step#299]
Create a Q/A for the demo: Managing git conflicts.

**Comment by AhalimZaki** [comment]
[Demo Link](http://devopsvisionsqa.mohamedradwan.com/?qa=644/what-are-the-steps-to-manage-git-conflicts)

**Comment by RehabAbotalep** [comment]
> [Demo Link](http://devopsvisionsqa.mohamedradwan.com/?qa=644/what-are-the-steps-to-manage-git-conflicts)

Reviewed, your review, please. @MohamedRadwan-DevOps
