### ISSUE TITLE
Improve module (17) demos description

### ISSUE THREAD

**Issue by AhalimZaki** [MohamedRadwan-DevOps/devops-step-by-step#301]
Improve module (17) demos description

**Comment by AhalimZaki** [comment]
Added: Demo 3 in module 17, Added the same demo in the TOC.
Edited: Demo 3 to be demo 4.

Fixed a small typo in module 16.

**Comment by RehabAbotalep** [comment]
@MohamedRadwan-DevOps Your final review, please.

**Comment by AhalimZaki** [comment]
@MohamedRadwan-DevOps Conflicts resolved.
