### ISSUE TITLE
Create the end of year survey

### ISSUE THREAD

**Issue by RehabAbotalep** [MohamedRadwan-DevOps/devops-step-by-step#592]

**Comment by RehabAbotalep** [comment]
@ShereenS @naja-ahmed Please comment here, so we can assign this item to you.

**Comment by naja-ahmed** [comment]
Ok

**Comment by RehabAbotalep** [comment]
Arrange for a meeting tomorrow.

**Comment by RehabAbotalep** [comment]
Generate the Link of the survey
Announcement in Discord
