### ISSUE TITLE
Create all the stories for moving the videos from YouTube to the new platform.

### ISSUE THREAD

**Issue by RehabAbotalep** [MohamedRadwan-DevOps/devops-step-by-step#593]
- [x]    New videos:
     - [x] Soft Skills
     - [x] Ask Me Anything
     - [x] Leadership & Group Advisory Meeting

- [x]  New Joiners:
     - [x] All Previous Events Sessions
     - [x] General Sessions
     - [x] Rehearse Sessions
     - [x] Old Mentoring Sessions
     - [x] Technical Sessions
     - [x] General Soft Skills Sessions (Old)

- [x]  Fundamental Course:
     - [x] Induction Session

- [x]  Master Course:
     - [x] Session (11)

**Comment by adamgamam** [comment]
Unsubscribe please

**Comment by RehabAbotalep** [comment]
Each physical lesson of New Joiners is a course for Mentor (Paid)
