### ISSUE TITLE
Fix how-to-contribute.md broken link

### ISSUE THREAD

**Issue by WaddahAzhary** [MohamedRadwan-DevOps/devops-step-by-step#610]
**Issue Description:**

The following link in [how-to-contribute.md](https://github.com/MohamedRadwan-DevOps/devops-step-by-step/blob/main/source/contribution/source/how-to-contribute.md) is broken:

- [FAQ](https://github.com/MohamedRadwan-DevOps/devops-step-by-step/blob/main/source/contribution/faq.md)  (line 71 in [how-to-contribute.md](https://github.com/MohamedRadwan-DevOps/devops-step-by-step/blob/main/source/contribution/source/how-to-contribute.md))

**Issue Details:**

When attempting to access the FAQ section through the provided link, it leads to 404 - page not found.

**Expected Behavior:**

The link should either point to a valid FAQ section or be updated to direct contributors to the correct resource for frequently asked questions.

**Steps to Reproduce:**

1. Navigate to the [how-to-contribute.md](https://github.com/MohamedRadwan-DevOps/devops-step-by-step/blob/main/source/contribution/source/how-to-contribute.md) file in the repository.
2. Scroll down to line 71 or search for the "FAQ" link.
3. Click on the link to access the FAQ section.

**Comment by ShereenS** [comment]
@WaddahAzhary Your effort is greatly appreciated!

**Comment by ShereenS** [comment]
@naja-ahmed Please comment here, so we can assign this item to you.

**Comment by naja-ahmed** [comment]
Ok

**Comment by AhalimZaki** [comment]
Thanks @naja-ahmed @ShereenS for the great effort
