### ISSUE TITLE
Bug course-schedule.md broken link 

### ISSUE THREAD

**Issue by naja-ahmed** [MohamedRadwan-DevOps/devops-step-by-step#630]
-Issue Description:
The following link in course-schedule.md is broken:
Date & Time Schedule(line 67 in course-schedule.md)

-Issue Details:
When attempting to access the Date & Time Schedule section through the provided link, it leads to 404 - page not found.

-Expected Behavior:
The link should point to a valid Date & Time Schedule section.

-Steps to Reproduce:
Navigate to Introduction to Information Technology
		Course Info and Prerequisites 
the course-schedule.md file in the repository.
Scroll down to line 67 or search for the "Date & Time Schedule" link.
Click on the link to access the Date & Time Schedule section.

**Comment by ShereenS** [comment]
@naja-ahmed Thanks, please note that the same issue exists in **Mastering Microsoft DevOps Solutions (Get Certified)** as well.
