### ISSUE TITLE
Fix devops-lessons-preparation.md broken links

### ISSUE THREAD

**Issue by WaddahAzhary** [MohamedRadwan-DevOps/devops-step-by-step#658]
**Issue Description:**
The following links in [devops-lessons-preparation.md/Module2](https://github.com/MohamedRadwan-DevOps/devops-step-by-step/blob/main/source/advanced-introduction-to-devops/source/devops-lessons-preparation.md#module-2-application-development-lifecycle-in-action) are not working as expected:

1.  [Enable IIS on your windows machine (windows feature) Webpage](https://gis.wsu.edu/portal/portalhelp/en/web-adaptor/latest/install/iis/enable-iis-10-components-server.htm) (Line 101 in [devops-lessons-preparation.md](https://github.com/MohamedRadwan-DevOps/devops-step-by-step/blob/main/source/advanced-introduction-to-devops/source/devops-lessons-preparation.md)  leads to the home page).
2. [REST API Webpage](https://www.c-sharpcorner.com/UploadFile/4b0136/restful-api-in-Asp-Net-introduction-of-rest-web-api/) (Line 129 in [devops-lessons-preparation.md](https://github.com/MohamedRadwan-DevOps/devops-step-by-step/blob/main/source/advanced-introduction-to-devops/source/devops-lessons-preparation.md) times out with error 522 after multiple attempts within a 24-hour period).
3. [Maintainability index metric Webpage](https://dartcodemetrics.dev/docs/metrics/maintainability-index) (Line 189 in [devops-lessons-preparation.md](https://github.com/MohamedRadwan-DevOps/devops-step-by-step/blob/main/source/advanced-introduction-to-devops/source/devops-lessons-preparation.md) leads to the home page).

**Issue Details:**
The links mentioned above don't direct to the correct web pages.

**Expected Behavior:**
The links should correctly lead to valid web pages.

**Steps to Reproduce:**
1. Navigate to the [devops-lessons-preparation.md/Module2](https://github.com/MohamedRadwan-DevOps/devops-step-by-step/blob/main/source/advanced-introduction-to-devops/source/devops-lessons-preparation.md#module-2-application-development-lifecycle-in-action) file in the repository.
2. Scroll down to line 101, 129, or 189 and click on them.

**Comment by ShereenS** [comment]
@WaddahAzhary Thanks a lot. Would you be interested in doing it?

**Comment by WaddahAzhary** [comment]
@ShereenS sure. please assign it to me.
