### ISSUE TITLE
Renaming members images according to our naming convention

### ISSUE THREAD

**Issue by RehabAbotalep** [MohamedRadwan-DevOps/devops-step-by-step#800]
We need to rename members' images according to our naming convention to be like the profile name.

Ex: (0)-Mohamed-Radwan.png
 
You can find all images on the Membership project under the images/members-images folder on the repo.

**Comment by RehabAbotalep** [comment]
@naja-ahmed Would you please comment here, so I can assign you?

**Comment by naja-ahmed** [comment]
Ok
